<a href="https://colab.research.google.com/github/tincorpai/Deep_Learning_Pytorch/blob/master/DataAnalysisAndReportPropensity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Install once if needed
install.packages("googledrive")

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

In [2]:
library(googledrive)
library(gargle)

Attaching package: ‘gargle’


The following object is masked from ‘package:googledrive’:

    request_make

In [3]:
install.packages('survey')

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

also installing the dependencies ‘minqa’, ‘numDeriv’, ‘mitools’, ‘RcppArmadillo’

In [4]:
library(survival)
library(survey)

Loading required package: grid

Loading required package: Matrix


Attaching package: ‘survey’


The following object is masked from ‘package:graphics’:

    dotchart

In [6]:
unlink("~/.cache/gargle", recursive = TRUE)

library(googledrive)
drive_auth(email = TRUE, scopes = "drive")

Please point your browser to the following url:

https://accounts.google.com/o/oauth2/v2/auth?client_id=603366585132-frjlouoa3s2ono25d2l9ukvhlsrlnr7k.apps.googleusercontent.com&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email&redirect_uri=https%3A%2F%2Fwww.tidyverse.org%2Fgoogle-callback%2F&response_type=code&state=4b70ab6fe586d7427b0da2cecb9b3faa&access_type=offline&prompt=consent

Enter authorization code: eyJjb2RlIjoiNC8wQWNpOThFOXNXcnVEVGVscldLNjQ4WDNIQ1pHbVA5cFJ0ZER4UUZ3Qy1uc21ycll1VFZCRlRaS3lIN2pyMTNVeXRXbUNrdyIsInN0YXRlIjoiNGI3MGFiNmZlNTg2ZDc0MjdiMGRhMmNlY2I5YjNmYWEifQ==

In [7]:
drive_has_token()
drive_user()

[1] TRUE

Logged in as:
• displayName: Taiwo Famuyiwa
• emailAddress: tincorpai@gmail.com

## **Dataset phmr_1_weak**

In [8]:
library(googledrive)

# The folder_id should be the actual Google Drive folder ID, not a local path.
# You can find the folder ID in the URL when browsing the folder in Google Drive.
# For example, if the URL is https://drive.google.com/drive/folders/YOUR_FOLDER_ID_HERE, then YOUR_FOLDER_ID_HERE is the folder ID.
# folder_id <- "/content/drive/MyDrive/paper_submission/propensity/overlap sensitivity/scenarios/overlapping/outliers/phmr_3_weak"
folder_id <- "17qjyOMWmcmGN5IRVl81VN0pBBhHzY_aZ"

#ordinary dataset
files <- drive_find(
  q = paste0("'", folder_id, "' in parents and trashed = false")
)

files

  name                id
1 samp_week_OX_OP.rds 1FubojwRKwA1mk7fSZlHnGfaOpWP_N21p
2 samp_week_OS_OP.rds 1pdK26Q-WR4LeP9FOkdHd8_ZQ4XUzFWTh
3 samp_week_OC_OP.rds 1s4M7IBCTyfdGzYuV4cS5pTKychFU3bUJ
4 samp_week_o0.rds    13vuXwaac_kGQOG_cfBDkybcOCWlHlL_W
  drive_resource                    <NA>           <NA>       <NA>
1 17qjyOMWmcmGN5IRVl81VN0pBBhHzY_aZ Taiwo Famuyiwa drive#user TRUE
2 17qjyOMWmcmGN5IRVl81VN0pBBhHzY_aZ Taiwo Famuyiwa drive#user TRUE
3 17qjyOMWmcmGN5IRVl81VN0pBBhHzY_aZ Taiwo Famuyiwa drive#user TRUE
4 17qjyOMWmcmGN5IRVl81VN0pBBhHzY_aZ Taiwo Famuyiwa drive#user TRUE
  <NA>                 <NA>
1 08860841588015227187 tincorpai@gmail.com
2 08860841588015227187 tincorpai@gmail.com
3 08860841588015227187 tincorpai@gmail.com
4 08860841588015227187 tincorpai@gmail.com
  <NA>
1 https://lh3.googleusercontent.com/a/ACg8ocKA3WiHNR22xxHMEEsyyxn1M3qLpvImnkua7Ywd8hMLXaLDFf4=s64
2 https://lh3.googleusercontent.com/a/ACg8ocKA3WiHNR22xxHMEEsyyxn1M3qLpvImnkua7Ywd8hMLXaLDFf4=s64
3 https://lh3.googleusercontent.com/a/ACg8ocKA3WiHNR22xxHMEEsyyxn1M3qLpvImnkua7Ywd8hMLXaLDFf4=s64
4 https://lh3.googleusercontent.com/a/ACg8ocKA3WiHNR22xxHMEEsyyxn1M3qLpvImnkua7Ywd8hMLXaLDFf4=s64
  <NA>           <NA>       <NA> <NA>                 <NA>
1 Taiwo Famuyiwa drive#user TRUE 08860841588015227187 tincorpai@gmail.com
2 Taiwo Famuyiwa drive#user TRUE 08860841588015227187 tincorpai@gmail.com
3 Taiwo Famuyiwa drive#user TRUE 08860841588015227187 tincorpai@gmail.com
4 Taiwo Famuyiwa drive#user TRUE 08860841588015227187 tincorpai@gmail.com
  <NA>
1 https://lh3.googleusercontent.com/a/ACg8ocKA3WiHNR22xxHMEEsyyxn1M3qLpvImnkua7Ywd8hMLXaLDFf4=s64
2 https://lh3.googleusercontent.com/a/ACg8ocKA3WiHNR22xxHMEEsyyxn1M3qLpvImnkua7Ywd8hMLXaLDFf4=s64
3 https://lh3.googleusercontent.com/a/ACg8ocKA3WiHNR22xxHMEEsyyxn1M3qLpvImnkua7Ywd8hMLXaLDFf4=s64
4 https://lh3.googleusercontent.com/a/ACg8ocKA3WiHNR22xxHMEEsyyxn1M3qLpvImnkua7Ywd8hMLXaLDFf4=s64
  <NA>             <NA>                 <NA> <NA>                <NA>
1 drive#permission 08860841588015227187 user tincorpai@gmail.com owner
2 drive#permission 08860841588015227187 user tincorpai@gmail.com owner
3 drive#permission 08860841588015227187 user tincorpai@gmail.com owner
4 drive#permission 08860841588015227187 user tincorpai@gmail.com owner
  <NA>
1 Taiwo Famuyiwa
2 Taiwo Famuyiwa
3 Taiwo Famuyiwa
4 Taiwo Famuyiwa
  <NA>
1 https://lh3.googleusercontent.com/a/ACg8ocKA3WiHNR22xxHMEEsyyxn1M3qLpvImnkua7Ywd8hMLXaLDFf4=s64
2 https://lh3.googleusercontent.com/a/ACg8ocKA3WiHNR22xxHMEEsyyxn1M3qLpvImnkua7Ywd8hMLXaLDFf4=s64
3 https://lh3.googleusercontent.com/a/ACg8ocKA3WiHNR22xxHMEEsyyxn1M3qLpvImnkua7Ywd8hMLXaLDFf4=s64
4 https://lh3.googleusercontent.com/a/ACg8ocKA3WiHNR22xxHMEEsyyxn1M3qLpvImnkua7Ywd8hMLXaLDFf4=s64
  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA> <NA> <NA>  <NA> <NA> <NA> <NA> <NA>
1 FALSE FALSE drive FALSE FALSE FALSE TRUE TRUE FALSE TRUE TRUE TRUE TRUE FALSE
2 FALSE FALSE drive FALSE FALSE FALSE TRUE TRUE FALSE TRUE TRUE TRUE TRUE FALSE
3 FALSE FALSE drive FALSE FALSE FALSE TRUE TRUE FALSE TRUE TRUE TRUE TRUE FALSE
4 FALSE FALSE drive FALSE FALSE FALSE TRUE TRUE FALSE TRUE TRUE TRUE TRUE FALSE
  <NA> <NA> <NA> <NA>  <NA> <NA> <NA> <NA> <NA>  <NA>  <NA> <NA> <NA> <NA>
1 TRUE TRUE TRUE FALSE TRUE TRUE TRUE TRUE FALSE FALSE TRUE TRUE TRUE FALSE
2 TRUE TRUE TRUE FALSE TRUE TRUE TRUE TRUE FALSE FALSE TRUE TRUE TRUE FALSE
3 TRUE TRUE TRUE FALSE TRUE TRUE TRUE TRUE FALSE FALSE TRUE TRUE TRUE FALSE
4 TRUE TRUE TRUE FALSE TRUE TRUE TRUE TRUE FALSE FALSE TRUE TRUE TRUE FALSE
  <NA> <NA>  <NA>  <NA> <NA> <NA> <NA> <NA> <NA>                 <NA>  <NA>
1 TRUE FALSE FALSE TRUE TRUE TRUE TRUE TRUE 08860841588015227187 FALSE TRUE
2 TRUE FALSE FALSE TRUE TRUE TRUE TRUE TRUE 08860841588015227187 FALSE TRUE
3 TRUE FALSE FALSE TRUE TRUE TRUE TRUE TRUE 08860841588015227187 FALSE TRUE
4 TRUE FALSE FALSE TRUE TRUE TRUE TRUE TRUE 08860841588015227187 FALSE TRUE
  <NA>  <NA>  <NA>  <NA>  <NA>       <NA>
1 FALSE FALSE FALSE FALSE drive#file 1FubojwRKwA1mk7fSZlHnGfaOpWP_N21p
2 FALSE FALSE FALSE FALSE drive#file 1FubojwRKwA1mk7fSZlHnGfaOpWP_N21p
3 FALSE FALSE FALSE FALSE drive#file 1FubojwRKwA1mk7fSZlHnGfaOpWP_N21p
4 FALSE FALSE FALSE FALSE drive#file 1FubojwRKwA1mk7fSZlHnGfaOpWP_N21p
  <NA>                <NA>               <NA>  <NA>  <NA>  <NA>
1 samp_week_OX_OP.rds application/x-gzip FALSE FALSE FALSE 3
2 samp_week_OX_OP.rds application/x-gzip FALSE FALSE FALSE 3
3 samp_week_OX_OP.rds application/x-gzip FALSE FALSE FALSE 3
4 samp_week_OX_OP.rds application/x-gzip FALSE FALSE FALSE 3
  <NA>
1 https://drive.google.com/uc?id=1FubojwRKwA1mk7fSZlHnGfaOpWP_N21p&export=download
2 https://drive.google.com/uc?id=1FubojwRKwA1mk7fSZlHnGfaOpWP_N21p&export=download
3 https://drive.google.com/uc?id=1FubojwRKwA1mk7fSZlHnGfaOpWP_N21p&export=download
4 https://drive.google.com/uc?id=1FubojwRKwA1mk7fSZlHnGfaOpWP_N21p&export=download
  <NA>
1 https://drive.google.com/file/d/1FubojwRKwA1mk7fSZlHnGfaOpWP_N21p/view?usp=drivesdk
2 https://drive.google.com/file/d/1FubojwRKwA1mk7fSZlHnGfaOpWP_N21p/view?usp=drivesdk
3 https://drive.google.com/file/d/1FubojwRKwA1mk7fSZlHnGfaOpWP_N21p/view?usp=drivesdk
4 https://drive.google.com/file/d/1FubojwRKwA1mk7fSZlHnGfaOpWP_N21p/view?usp=drivesdk
  <NA>
1 https://drive-thirdparty.googleusercontent.com/16/type/application/x-gzip
2 https://drive-thirdparty.googleusercontent.com/16/type/application/x-gzip
3 https://drive-thirdparty.googleusercontent.com/16/type/application/x-gzip
4 https://drive-thirdparty.googleusercontent.com/16/type/application/x-gzip
  <NA>  <NA> <NA> <NA>                     <NA>
1 FALSE 0    TRUE 2026-03-22T13:29:53.784Z 2026-03-22T13:29:53.784Z
2 FALSE 0    TRUE 2026-03-22T13:29:53.784Z 2026-03-22T13:29:53.784Z
3 FALSE 0    TRUE 2026-03-22T13:29:53.784Z 2026-03-22T13:29:53.784Z
4 FALSE 0    TRUE 2026-03-22T13:29:53.784Z 2026-03-22T13:29:53.784Z
  <NA>                     <NA>                     <NA> <NA>  <NA> <NA> <NA>
1 2026-03-22T11:34:48.000Z 2026-03-22T11:34:48.000Z TRUE FALSE TRUE TRUE FALSE
2 2026-03-22T11:34:48.000Z 2026-03-22T11:34:48.000Z TRUE FALSE TRUE TRUE FALSE
3 2026-03-22T11:34:48.000Z 2026-03-22T11:34:48.000Z TRUE FALSE TRUE TRUE FALSE
4 2026-03-22T11:34:48.000Z 2026-03-22T11:34:48.000Z TRUE FALSE TRUE TRUE FALSE
  <NA> <NA>                <NA> <NA> <NA>
1 TRUE samp_week_OX_OP.rds rds  rds  2444cb8df7b979c0975858f30dc15a41
2 TRUE samp_week_OX_OP.rds rds  rds  2444cb8df7b979c0975858f30dc15a41
3 TRUE samp_week_OX_OP.rds rds  rds  2444cb8df7b979c0975858f30dc15a41
4 TRUE samp_week_OX_OP.rds rds  rds  2444cb8df7b979c0975858f30dc15a41
  <NA>
1 91d90d337e51233fe26babae8d28fc72d97435b7
2 91d90d337e51233fe26babae8d28fc72d97435b7
3 91d90d337e51233fe26babae8d28fc72d97435b7
4 91d90d337e51233fe26babae8d28fc72d97435b7
  <NA>                                                             <NA>
1 28e586d83bab230b3517fe10f51ff134e321330514545780ab0cbc81e1b2035f 547446652
2 28e586d83bab230b3517fe10f51ff134e321330514545780ab0cbc81e1b2035f 547446652
3 28e586d83bab230b3517fe10f51ff134e321330514545780ab0cbc81e1b2035f 547446652
4 28e586d83bab230b3517fe10f51ff134e321330514545780ab0cbc81e1b2035f 547446652
  <NA>      <NA>                                                <NA>  <NA>
1 547446652 0B-ncyGuPmiZ6RnpDTTdqTEVCQ0JkSHc3aE9jQlJrK3dOYThRPQ FALSE FALSE
2 547446652 0B-ncyGuPmiZ6RnpDTTdqTEVCQ0JkSHc3aE9jQlJrK3dOYThRPQ FALSE FALSE
3 547446652 0B-ncyGuPmiZ6RnpDTTdqTEVCQ0JkSHc3aE9jQlJrK3dOYThRPQ FALSE FALSE
4 547446652 0B-ncyGuPmiZ6RnpDTTdqTEVCQ0JkSHc3aE9jQlJrK3dOYThRPQ FALSE FALSE
  <NA>                              <NA>           <NA>       <NA>
1 17qjyOMWmcmGN5IRVl81VN0pBBhHzY_aZ Taiwo Famuyiwa drive#user TRUE
2 17qjyOMWmcmGN5IRVl81VN0pBBhHzY_aZ Taiwo Famuyiwa drive#user TRUE
3 17qjyOMWmcmGN5IRVl81VN0pBBhHzY_aZ Taiwo Famuyiwa drive#user TRUE
4 17qjyOMWmcmGN5IRVl81VN0pBBhHzY_aZ Taiwo Famuyiwa drive#user TRUE
  <NA>                 <NA>
1 08860841588015227187 tincorpai@gmail.com
2 08860841588015227187 tincorpai@gmail.com
3 08860841588015227187 tincorpai@gmail.com
4 08860841588015227187 tincorpai@gmail.com
  <NA>
1 https://lh3.googleusercontent.com/a/ACg8ocKA3WiHNR22xxHMEEsyyxn1M3qLpvImnkua7Ywd8hMLXaLDFf4=s64
2 https://lh3.googleusercontent.com/a/ACg8ocKA3WiHNR22xxHMEEsyyxn1M3qLpvImnkua7Ywd8hMLXaLDFf4=s64
3 https://lh3.googleusercontent.com/a/ACg8ocKA3WiHNR22xxHMEEsyyxn1M3qLpvImnkua7Ywd8hMLXaLDFf4=s64
4 https://lh3.googleusercontent.com/a/ACg8ocKA3WiHNR22xxHMEEsyyxn1M3qLpvImnkua7Ywd8hMLXaLDFf4=s64
  <NA>           <NA>       <NA> <NA>                 <NA>
1 Taiwo Famuyiwa drive#user TRUE 08860841588015227187 tincorpai@gmail.com
2 Taiwo Famuyiwa drive#user TRUE 08860841588015227187 tincorpai@gmail.com
3 Taiwo Famuyiwa drive#user TRUE 08860841588015227187 tincorpai@gmail.com
4 Taiwo Famuyiwa drive#user TRUE 08860841588015227187 tincorpai@gmail.com
  <NA>
1 https://lh3.googleusercontent.com/a/ACg8ocKA3WiHNR22xxHMEEsyyxn1M3qLpvImnkua7Ywd8hMLXaLDFf4=s64
2 https://lh3.googleusercontent.com/a/ACg8ocKA3WiHNR22xxHMEEsyyxn1M3qLpvImnkua7Ywd8hMLXaLDFf4=s64
3 https://lh3.googleusercontent.com/a/ACg8ocKA3WiHNR22xxHMEEsyyxn1M3qLpvImnkua7Ywd8hMLXaLDFf4=s64
4 https://lh3.googleusercontent.com/a/ACg8ocKA3WiHNR22xxHMEEsyyxn1M3qLpvImnkua7Ywd8hMLXaLDFf4=s64
  <NA>             <NA>                 <NA> <NA>                <NA>
1 drive#permission 08860841588015227187 user tincorpai@gmail.com owner
2 drive#permission 08860841588015227187 user tincorpai@gmail.com owner
3 drive#permission 08860841588015227187 user tincorpai@gmail.com owner
4 drive#permission 08860841588015227187 user tincorpai@gmail.com owner
  <NA>
1 Taiwo Famuyiwa
2 Taiwo Famuyiwa
3 Taiwo Famuyiwa
4 Taiwo Famuyiwa
  <NA>
1 https://lh3.googleusercontent.com/a/ACg8ocKA3WiHNR22xxHMEEsyyxn1M3qLpvImnkua7Ywd8hMLXaLDFf4=s64
2 https://lh3.googleusercontent.com/a/ACg8ocKA3WiHNR22xxHMEEsyyxn1M3qLpvImnkua7Ywd8hMLXaLDFf4=s64
3 https://lh3.googleusercontent.com/a/ACg8ocKA3WiHNR22xxHMEEsyyxn1M3qLpvImnkua7Ywd8hMLXaLDFf4=s64
4 https://lh3.googleusercontent.com/a/ACg8ocKA3WiHNR22xxHMEEsyyxn1M3qLpvImnkua7Ywd8hMLXaLDFf4=s64
  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA> <NA> <NA>  <NA> <NA> <NA> <NA> <NA>
1 FALSE FALSE drive FALSE FALSE FALSE TRUE TRUE FALSE TRUE TRUE TRUE TRUE FALSE
2 FALSE FALSE drive FALSE FALSE FALSE TRUE TRUE FALSE TRUE TRUE TRUE TRUE FALSE
3 FALSE FALSE drive FALSE FALSE FALSE TRUE TRUE FALSE TRUE TRUE TRUE TRUE FALSE
4 FALSE FALSE drive FALSE FALSE FALSE TRUE TRUE FALSE TRUE TRUE TRUE TRUE FALSE
  <NA> <NA> <NA> <NA>  <NA> <NA> <NA> <NA> <NA>  <NA>  <NA> <NA> <NA> <NA>
1 TRUE TRUE TRUE FALSE TRUE TRUE TRUE TRUE FALSE FALSE TRUE TRUE TRUE FALSE
2 TRUE TRUE TRUE FALSE TRUE TRUE TRUE TRUE FALSE FALSE TRUE TRUE TRUE FALSE
3 TRUE TRUE TRUE FALSE TRUE TRUE TRUE TRUE FALSE FALSE TRUE TRUE TRUE FALSE
4 TRUE TRUE TRUE FALSE TRUE TRUE TRUE TRUE FALSE FALSE TRUE TRUE TRUE FALSE
  <NA> <NA>  <NA>  <NA> <NA> <NA> <NA> <NA> <NA>                 <NA>  <NA>
1 TRUE FALSE FALSE TRUE TRUE TRUE TRUE TRUE 08860841588015227187 FALSE TRUE
2 TRUE FALSE FALSE TRUE TRUE TRUE TRUE TRUE 08860841588015227187 FALSE TRUE
3 TRUE FALSE FALSE TRUE TRUE TRUE TRUE TRUE 08860841588015227187 FALSE TRUE
4 TRUE FALSE FALSE TRUE TRUE TRUE TRUE TRUE 08860841588015227187 FALSE TRUE
  <NA>  <NA>  <NA>  <NA>  <NA>       <NA>
1 FALSE FALSE FALSE FALSE drive#file 1pdK26Q-WR4LeP9FOkdHd8_ZQ4XUzFWTh
2 FALSE FALSE FALSE FALSE drive#file 1pdK26Q-WR4LeP9FOkdHd8_ZQ4XUzFWTh
3 FALSE FALSE FALSE FALSE drive#file 1pdK26Q-WR4LeP9FOkdHd8_ZQ4XUzFWTh
4 FALSE FALSE FALSE FALSE drive#file 1pdK26Q-WR4LeP9FOkdHd8_ZQ4XUzFWTh
  <NA>                <NA>               <NA>  <NA>  <NA>  <NA>
1 samp_week_OS_OP.rds application/x-gzip FALSE FALSE FALSE 3
2 samp_week_OS_OP.rds application/x-gzip FALSE FALSE FALSE 3
3 samp_week_OS_OP.rds application/x-gzip FALSE FALSE FALSE 3
4 samp_week_OS_OP.rds application/x-gzip FALSE FALSE FALSE 3
  <NA>
1 https://drive.google.com/uc?id=1pdK26Q-WR4LeP9FOkdHd8_ZQ4XUzFWTh&export=download
2 https://drive.google.com/uc?id=1pdK26Q-WR4LeP9FOkdHd8_ZQ4XUzFWTh&export=download
3 https://drive.google.com/uc?id=1pdK26Q-WR4LeP9FOkdHd8_ZQ4XUzFWTh&export=download
4 https://drive.google.com/uc?id=1pdK26Q-WR4LeP9FOkdHd8_ZQ4XUzFWTh&export=download
  <NA>
1 https://drive.google.com/file/d/1pdK26Q-WR4LeP9FOkdHd8_ZQ4XUzFWTh/view?usp=drivesdk
2 https://drive.google.com/file/d/1pdK26Q-WR4LeP9FOkdHd8_ZQ4XUzFWTh/view?usp=drivesdk
3 https://drive.google.com/file/d/1pdK26Q-WR4LeP9FOkdHd8_ZQ4XUzFWTh/view?usp=drivesdk
4 https://drive.google.com/file/d/1pdK26Q-WR4LeP9FOkdHd8_ZQ4XUzFWTh/view?usp=drivesdk
  <NA>
1 https://drive-thirdparty.googleusercontent.com/16/type/application/x-gzip
2 https://drive-thirdparty.googleusercontent.com/16/type/application/x-gzip
3 https://drive-thirdparty.googleusercontent.com/16/type/application/x-gzip
4 https://drive-thirdparty.googleusercontent.com/16/type/application/x-gzip
  <NA>  <NA> <NA> <NA>                     <NA>
1 FALSE 0    TRUE 2026-03-22T13:29:29.869Z 2026-03-22T13:29:29.869Z
2 FALSE 0    TRUE 2026-03-22T13:29:29.869Z 2026-03-22T13:29:29.869Z
3 FALSE 0    TRUE 2026-03-22T13:29:29.869Z 2026-03-22T13:29:29.869Z
4 FALSE 0    TRUE 2026-03-22T13:29:29.869Z 2026-03-22T13:29:29.869Z
  <NA>                     <NA>                     <NA> <NA>  <NA> <NA> <NA>
1 2026-03-22T11:58:46.000Z 2026-03-22T11:58:46.000Z TRUE FALSE TRUE TRUE FALSE
2 2026-03-22T11:58:46.000Z 2026-03-22T11:58:46.000Z TRUE FALSE TRUE TRUE FALSE
3 2026-03-22T11:58:46.000Z 2026-03-22T11:58:46.000Z TRUE FALSE TRUE TRUE FALSE
4 2026-03-22T11:58:46.000Z 2026-03-22T11:58:46.000Z TRUE FALSE TRUE TRUE FALSE
  <NA> <NA>                <NA> <NA> <NA>
1 TRUE samp_week_OS_OP.rds rds  rds  374cef7833e41c2027016762e523614a
2 TRUE samp_week_OS_OP.rds rds  rds  374cef7833e41c2027016762e523614a
3 TRUE samp_week_OS_OP.rds rds  rds  374cef7833e41c2027016762e523614a
4 TRUE samp_week_OS_OP.rds rds  rds  374cef7833e41c2027016762e523614a
  <NA>
1 b83841fc0c12be4da5aa64c92705c76991c52447
2 b83841fc0c12be4da5aa64c92705c76991c52447
3 b83841fc0c12be4da5aa64c92705c76991c52447
4 b83841fc0c12be4da5aa64c92705c76991c52447
  <NA>                                                             <NA>
1 27aced8ff892a6a991b95874b36bdb246067cb046da78744465bf049fbc31b5e 547426312
2 27aced8ff892a6a991b95874b36bdb246067cb046da78744465bf049fbc31b5e 547426312
3 27aced8ff892a6a991b95874b36bdb246067cb046da78744465bf049fbc31b5e 547426312
4 27aced8ff892a6a991b95874b36bdb246067cb046da78744465bf049fbc31b5e 547426312
  <NA>      <NA>                                                <NA>  <NA>
1 547426312 0B-ncyGuPmiZ6K3N0NUFvdGxBZWNtdGtGSWdJcEl4Tk5USUFVPQ FALSE FALSE
2 547426312 0B-ncyGuPmiZ6K3N0NUFvdGxBZWNtdGtGSWdJcEl4Tk5USUFVPQ FALSE FALSE
3 547426312 0B-ncyGuPmiZ6K3N0NUFvdGxBZWNtdGtGSWdJcEl4Tk5USUFVPQ FALSE FALSE
4 547426312 0B-ncyGuPmiZ6K3N0NUFvdGxBZWNtdGtGSWdJcEl4Tk5USUFVPQ FALSE FALSE
  <NA>                              <NA>           <NA>       <NA>
1 17qjyOMWmcmGN5IRVl81VN0pBBhHzY_aZ Taiwo Famuyiwa drive#user TRUE
2 17qjyOMWmcmGN5IRVl81VN0pBBhHzY_aZ Taiwo Famuyiwa drive#user TRUE
3 17qjyOMWmcmGN5IRVl81VN0pBBhHzY_aZ Taiwo Famuyiwa drive#user TRUE
4 17qjyOMWmcmGN5IRVl81VN0pBBhHzY_aZ Taiwo Famuyiwa drive#user TRUE
  <NA>                 <NA>
1 08860841588015227187 tincorpai@gmail.com
2 08860841588015227187 tincorpai@gmail.com
3 08860841588015227187 tincorpai@gmail.com
4 08860841588015227187 tincorpai@gmail.com
  <NA>
1 https://lh3.googleusercontent.com/a/ACg8ocKA3WiHNR22xxHMEEsyyxn1M3qLpvImnkua7Ywd8hMLXaLDFf4=s64
2 https://lh3.googleusercontent.com/a/ACg8ocKA3WiHNR22xxHMEEsyyxn1M3qLpvImnkua7Ywd8hMLXaLDFf4=s64
3 https://lh3.googleusercontent.com/a/ACg8ocKA3WiHNR22xxHMEEsyyxn1M3qLpvImnkua7Ywd8hMLXaLDFf4=s64
4 https://lh3.googleusercontent.com/a/ACg8ocKA3WiHNR22xxHMEEsyyxn1M3qLpvImnkua7Ywd8hMLXaLDFf4=s64
  <NA>           <NA>       <NA> <NA>                 <NA>
1 Taiwo Famuyiwa drive#user TRUE 08860841588015227187 tincorpai@gmail.com
2 Taiwo Famuyiwa drive#user TRUE 08860841588015227187 tincorpai@gmail.com
3 Taiwo Famuyiwa drive#user TRUE 08860841588015227187 tincorpai@gmail.com
4 Taiwo Famuyiwa drive#user TRUE 08860841588015227187 tincorpai@gmail.com
  <NA>
1 https://lh3.googleusercontent.com/a/ACg8ocKA3WiHNR22xxHMEEsyyxn1M3qLpvImnkua7Ywd8hMLXaLDFf4=s64
2 https://lh3.googleusercontent.com/a/ACg8ocKA3WiHNR22xxHMEEsyyxn1M3qLpvImnkua7Ywd8hMLXaLDFf4=s64
3 https://lh3.googleusercontent.com/a/ACg8ocKA3WiHNR22xxHMEEsyyxn1M3qLpvImnkua7Ywd8hMLXaLDFf4=s64
4 https://lh3.googleusercontent.com/a/ACg8ocKA3WiHNR22xxHMEEsyyxn1M3qLpvImnkua7Ywd8hMLXaLDFf4=s64
  <NA>             <NA>                 <NA> <NA>                <NA>
1 drive#permission 08860841588015227187 user tincorpai@gmail.com owner
2 drive#permission 08860841588015227187 user tincorpai@gmail.com owner
3 drive#permission 08860841588015227187 user tincorpai@gmail.com owner
4 drive#permission 08860841588015227187 user tincorpai@gmail.com owner
  <NA>
1 Taiwo Famuyiwa
2 Taiwo Famuyiwa
3 Taiwo Famuyiwa
4 Taiwo Famuyiwa
  <NA>
1 https://lh3.googleusercontent.com/a/ACg8ocKA3WiHNR22xxHMEEsyyxn1M3qLpvImnkua7Ywd8hMLXaLDFf4=s64
2 https://lh3.googleusercontent.com/a/ACg8ocKA3WiHNR22xxHMEEsyyxn1M3qLpvImnkua7Ywd8hMLXaLDFf4=s64
3 https://lh3.googleusercontent.com/a/ACg8ocKA3WiHNR22xxHMEEsyyxn1M3qLpvImnkua7Ywd8hMLXaLDFf4=s64
4 https://lh3.googleusercontent.com/a/ACg8ocKA3WiHNR22xxHMEEsyyxn1M3qLpvImnkua7Ywd8hMLXaLDFf4=s64
  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA> <NA> <NA>  <NA> <NA> <NA> <NA> <NA>
1 FALSE FALSE drive FALSE FALSE FALSE TRUE TRUE FALSE TRUE TRUE TRUE TRUE FALSE
2 FALSE FALSE drive FALSE FALSE FALSE TRUE TRUE FALSE TRUE TRUE TRUE TRUE FALSE
3 FALSE FALSE drive FALSE FALSE FALSE TRUE TRUE FALSE TRUE TRUE TRUE TRUE FALSE
4 FALSE FALSE drive FALSE FALSE FALSE TRUE TRUE FALSE TRUE TRUE TRUE TRUE FALSE
  <NA> <NA> <NA> <NA>  <NA> <NA> <NA> <NA> <NA>  <NA>  <NA> <NA> <NA> <NA>
1 TRUE TRUE TRUE FALSE TRUE TRUE TRUE TRUE FALSE FALSE TRUE TRUE TRUE FALSE
2 TRUE TRUE TRUE FALSE TRUE TRUE TRUE TRUE FALSE FALSE TRUE TRUE TRUE FALSE
3 TRUE TRUE TRUE FALSE TRUE TRUE TRUE TRUE FALSE FALSE TRUE TRUE TRUE FALSE
4 TRUE TRUE TRUE FALSE TRUE TRUE TRUE TRUE FALSE FALSE TRUE TRUE TRUE FALSE
  <NA> <NA>  <NA>  <NA> <NA> <NA> <NA> <NA> <NA>                 <NA>  <NA>
1 TRUE FALSE FALSE TRUE TRUE TRUE TRUE TRUE 08860841588015227187 FALSE TRUE
2 TRUE FALSE FALSE TRUE TRUE TRUE TRUE TRUE 08860841588015227187 FALSE TRUE
3 TRUE FALSE FALSE TRUE TRUE TRUE TRUE TRUE 08860841588015227187 FALSE TRUE
4 TRUE FALSE FALSE TRUE TRUE TRUE TRUE TRUE 08860841588015227187 FALSE TRUE
  <NA>  <NA>  <NA>  <NA>  <NA>       <NA>
1 FALSE FALSE FALSE FALSE drive#file 1s4M7IBCTyfdGzYuV4cS5pTKychFU3bUJ
2 FALSE FALSE FALSE FALSE drive#file 1s4M7IBCTyfdGzYuV4cS5pTKychFU3bUJ
3 FALSE FALSE FALSE FALSE drive#file 1s4M7IBCTyfdGzYuV4cS5pTKychFU3bUJ
4 FALSE FALSE FALSE FALSE drive#file 1s4M7IBCTyfdGzYuV4cS5pTKychFU3bUJ
  <NA>                <NA>               <NA>  <NA>  <NA>  <NA>
1 samp_week_OC_OP.rds application/x-gzip FALSE FALSE FALSE 3
2 samp_week_OC_OP.rds application/x-gzip FALSE FALSE FALSE 3
3 samp_week_OC_OP.rds application/x-gzip FALSE FALSE FALSE 3
4 samp_week_OC_OP.rds application/x-gzip FALSE FALSE FALSE 3
  <NA>
1 https://drive.google.com/uc?id=1s4M7IBCTyfdGzYuV4cS5pTKychFU3bUJ&export=download
2 https://drive.google.com/uc?id=1s4M7IBCTyfdGzYuV4cS5pTKychFU3bUJ&export=download
3 https://drive.google.com/uc?id=1s4M7IBCTyfdGzYuV4cS5pTKychFU3bUJ&export=download
4 https://drive.google.com/uc?id=1s4M7IBCTyfdGzYuV4cS5pTKychFU3bUJ&export=download
  <NA>
1 https://drive.google.com/file/d/1s4M7IBCTyfdGzYuV4cS5pTKychFU3bUJ/view?usp=drivesdk
2 https://drive.google.com/file/d/1s4M7IBCTyfdGzYuV4cS5pTKychFU3bUJ/view?usp=drivesdk
3 https://drive.google.com/file/d/1s4M7IBCTyfdGzYuV4cS5pTKychFU3bUJ/view?usp=drivesdk
4 https://drive.google.com/file/d/1s4M7IBCTyfdGzYuV4cS5pTKychFU3bUJ/view?usp=drivesdk
  <NA>
1 https://drive-thirdparty.googleusercontent.com/16/type/application/x-gzip
2 https://drive-thirdparty.googleusercontent.com/16/type/application/x-gzip



---

#### **Helper Functions**

###### **Weighted AKME Function**

In [18]:
akme_survival <- function(dat,
                          z_value,
                          time_var = "T",
                          event_var = "delta",
                          treat_var = "Z",
                          weight_var = "w") {

  dsub <- dat[dat[[treat_var]] == z_value, , drop = FALSE]

  t <- dsub[[time_var]]
  d <- dsub[[event_var]]
  w <- dsub[[weight_var]]

  # event times only
  event_times <- sort(unique(t[d == 1]))

  if (length(event_times) == 0) {
    return(data.frame(time = 0, surv = 1))
  }

  surv <- numeric(length(event_times))
  s_now <- 1

  for (j in seq_along(event_times)) {
    tj <- event_times[j]

    # weighted risk set at tj
    Yw <- sum(w[t >= tj], na.rm = TRUE)

    # weighted events at tj
    dw <- sum(w[t == tj & d == 1], na.rm = TRUE)

    if (Yw > 0) {
      s_now <- s_now * (1 - dw / Yw)
    }

    surv[j] <- s_now
  }

  out <- data.frame(
    time = c(0, event_times),
    surv = c(1, surv)
  )

  rownames(out) <- NULL
  out
}

###### **Extract Survival quantile**

In [19]:
surv_quantile <- function(S_df, q) {
  target <- 1 - q
  idx <- which(S_df$surv <= target)[1]

  if (is.na(idx)) return(NA_real_)
  S_df$time[idx]
}

##### **Function to compute PSQE from AKME**

In [20]:
compute_psqe_from_akme <- function(dat, weight_var = "w") {

  S1 <- akme_survival(dat, z_value = 1, weight_var = weight_var)
  S0 <- akme_survival(dat, z_value = 0, weight_var = weight_var)

  q_levels <- c(0.25, 0.50, 0.75)

  Q1 <- sapply(q_levels, function(q) surv_quantile(S1, q))
  Q0 <- sapply(q_levels, function(q) surv_quantile(S0, q))

  out <- data.frame(
    quantile = q_levels,
    Q1 = Q1,
    Q0 = Q0,
    PSQE = Q1 - Q0
  )

  list(
    S1 = S1,
    S0 = S0,
    psqe = out
  )
}

##### **Function for MEthod I code**

In [21]:
akme_method1 <- function(dat) {
  dat$w <- dat$w_ps
  compute_psqe_from_akme(dat, weight_var = "w")
}

##### **Function for MEthod II code**

In [22]:
akme_method2 <- function(dat) {
  dat$w <- dat$W_final
  compute_psqe_from_akme(dat, weight_var = "w")
}

##### **Function for MEthod II code**

In [23]:
akme_method3 <- function(dat,
                         ps_formula = Z ~ X1 + X2 + X3 + X4 + X5 + X_61 + X_62) {

  # Step 1: survey-weighted PS model
  design_ps <- svydesign(
    ids = ~cluster,
    strata = ~stratum,
    weights = ~w_svy,
    data = dat,
    nest = TRUE
  )

  ps_fit <- svyglm(
    ps_formula,
    design = design_ps,
    family = quasibinomial()
  )

  ps_hat <- predict(ps_fit, type = "response")

  # avoid 0 and 1
  eps <- 1e-6
  ps_hat <- pmin(pmax(ps_hat, eps), 1 - eps)

  # Step 2: IPTW
  w_ps_m3 <- ifelse(dat$Z == 1, 1 / ps_hat, 1 / (1 - ps_hat))

  # Step 3: final combined weight
  dat$w <- dat$w_svy * w_ps_m3

  compute_psqe_from_akme(dat, weight_var = "w")
}

In [24]:
print_psqe_results <- function(res_M1, res_M2, res_M3) {
  cat("\nMethod I PSQE\n")
  print(res_M1$psqe)

  cat("\nMethod II PSQE\n")
  print(res_M2$psqe)

  cat("\nMethod III PSQE\n")
  print(res_M3$psqe)
}

###  **Import the ordinary dataset**

In [16]:
file_o0 <- files[files$name == 'samp_week_o0.rds', ]

In [17]:
drive_download(
  file = file_o0$id,
  path = "samp_week_o0.rds",
  overwrite = TRUE
)

File downloaded:

• samp_week_o0.rds <id: 13vuXwaac_kGQOG_cfBDkybcOCWlHlL_W>

Saved locally as:

• samp_week_o0.rds

In [25]:
obj <- readRDS("samp_week_o0.rds")

In [26]:
dat <- obj[[1]]

In [27]:
res_M1 <- akme_method1(dat)
res_M2 <- akme_method2(dat)
res_M3 <- akme_method3(dat)

print_psqe_results(res_M1, res_M2, res_M3)

Method I PSQE
  quantile       Q1        Q0     PSQE
1     0.25 145.2411  91.90199 53.33909
2     0.50 208.7099 147.96661 60.74327
3     0.75 309.9673 222.92123 87.04609

Method II PSQE
  quantile       Q1        Q0     PSQE
1     0.25 143.2158  93.76726 49.44857
2     0.50 208.2061 147.76726 60.43883
3     0.75 309.9673 223.27760 86.68972

Method III PSQE
  quantile       Q1        Q0     PSQE
1     0.25 143.2516  93.76726 49.48437
2     0.50 204.5760 147.73860 56.83742
3     0.75 303.2751 223.27760 79.99749

In [28]:
run_one_psqe <- function(dat) {
  list(
    M1 = akme_method1(dat)$psqe,
    M2 = akme_method2(dat)$psqe,
    M3 = akme_method3(dat)$psqe
  )
}

In [29]:
run_psqe_batch <- function(all_dat, start = 1, end = length(all_dat)) {

  end <- min(end, length(all_dat))

  results <- vector("list", end - start + 1)

  for (i in start:end) {
    dat <- all_dat[[i]]

    results[[i - start + 1]] <- tryCatch(
      run_one_psqe(dat),
      error = function(e) {
        message(sprintf("Error at dataset %d: %s", i, e$message))
        NULL
      }
    )
  }

  names(results) <- paste0("rep_", start:end)
  results
}

In [30]:
# Batch 1: 1–100
res_1_100 <- run_psqe_batch(obj, 1, 100)

In [31]:
# Batch 2: 101–200
res_101_200 <- run_psqe_batch(obj, 101, 200)

In [32]:
res_201_300 <- run_psqe_batch(obj, 201, 300)

In [33]:
res_301_400 <- run_psqe_batch(obj, 301, 400)

In [34]:
res_401_500 <- run_psqe_batch(obj, 401, 500)

In [35]:
res_501_600 <- run_psqe_batch(obj, 501, 600)

In [36]:
res_601_700 <- run_psqe_batch(obj,601, 700)

In [37]:
res_701_800 <- run_psqe_batch(obj, 701, 800)

In [38]:
res_801_900 <- run_psqe_batch(obj, 801, 900)

In [39]:
res_901_1000 <- run_psqe_batch(obj, 901, 1000)

In [84]:
res_to_df <- function(res_obj) {
  do.call(rbind, lapply(names(res_obj), function(rep_name) {
    rep_res <- res_obj[[rep_name]]

    do.call(rbind, lapply(names(rep_res), function(method_name) {
      df <- rep_res[[method_name]]
      df$rep <- rep_name
      df$method <- method_name
      df
    }))
  }))
}

In [88]:
res_1_100_df <- res_to_df(res_1_100)
res_101_200_df <- res_to_df(res_101_200)
res_201_300_df <- res_to_df(res_201_300)
res_301_400_df <- res_to_df(res_301_400)
res_401_500_df <- res_to_df(res_401_500)
res_501_600_df <- res_to_df(res_501_600)
res_601_700_df <- res_to_df(res_601_700)
res_701_800_df <- res_to_df(res_701_800)
res_801_900_df <- res_to_df(res_801_900)
res_res_901_1000_df <- res_to_df(res_901_1000)

In [90]:
write.csv(res_1_100_df, "res_1_100_df.csv", row.names = FALSE)

In [92]:
system("python3 - <<'PY'\nfrom google.colab import files\nfiles.download('res_1_100_df.csv')\nPY")

In [89]:
head(res_res_901_1000_df)

  quantile Q1       Q0       PSQE     rep     method
1 0.25     131.4553 102.4709 28.98442 rep_901 M1
2 0.50     204.9982 163.2741 41.72412 rep_901 M1
3 0.75     313.9630 237.8926 76.07044 rep_901 M1
4 0.25     135.2576 101.2675 33.99004 rep_901 M2
5 0.50     204.9982 161.0156 43.98267 rep_901 M2
6 0.75     306.8167 237.6535 69.16318 rep_901 M2

In [80]:
system("python3 - <<'PY'
from google.colab import files
files.download('all_batch_results.zip')
PY")

##### Saving data to folder

In [83]:
folder_path <- "/content/driveMyDrive/paper_submission/propensity/overlap sensitivity/scenarios/overlapping/outliers/phm_1_weak_analysis"

if (!dir.exists(folder_path)) {
  dir.create(folder_path, recursive = TRUE)
}

saveRDS(res_1_100, file.path(folder_path, "res_1_100.rds"))

In [43]:
save_to_colab_drive <- function(obj,
                                filename,
                                folder = "/content/driveMyDrive/paper_submission/propensity/overlap sensitivity/scenarios/overlapping/outliers/phm_1_weak_analysis") {

  # check drive mount
  if (!dir.exists("/content/drive/MyDrive")) {
    stop("Google Drive is not mounted.")
  }

  # create folder if needed
  if (!dir.exists(folder)) {
    dir.create(folder, recursive = TRUE, showWarnings = FALSE)
  }

  # full output path
  full_path <- file.path(folder, filename)

  # save
  saveRDS(obj, full_path)

  # verify
  if (file.exists(full_path)) {
    message("Saved successfully to: ", full_path)
  } else {
    stop("File was not saved. Check path and permissions.")
  }

  return(full_path)
}

In [125]:
save_to_colab_drive(
  res_1_100,
  "psqe_batch_1_100.rds"
)

ERROR: Error in save_to_colab_drive(res_1_100, "psqe_batch_1_100.rds"): Google Drive is not mounted.

In [ ]:
save_to_colab_drive(res_201_300, "psqe_batch_201_300.rds")

In [ ]:
save_to_drive <- function(obj,
                          filename,
                          folder = "MyDrive/psqe_results") {

  # full path in Colab
  base_path <- file.path("/content/drive", folder)

  # create folder if it does not exist
  if (!dir.exists(base_path)) {
    dir.create(base_path, recursive = TRUE)
  }

  # full file path
  full_path <- file.path(base_path, filename)

  # save file
  saveRDS(obj, full_path)

  message(sprintf("Saved to: %s", full_path))
}

### **Import dataset with censoring and propensity outliers**

In [60]:
file_weak_OC_OP <- files[files$name == 'samp_week_OC_OP.rds', ]

In [61]:
drive_download(
  file = file_weak_OC_OP$id,
  path = "samp_week_OC_OP.rds",
  overwrite = TRUE
)

File downloaded:

• samp_week_OC_OP.rds <id: 1s4M7IBCTyfdGzYuV4cS5pTKychFU3bUJ>

Saved locally as:

• samp_week_OC_OP.rds

In [62]:
obj_OC_OP <- readRDS("samp_week_OC_OP.rds")

### **Import dataset with survival outliers and propensity outliers**

In [15]:
file_week_OS_OP <- files[files$name == 'samp_week_OS_OP.rds', ]

In [16]:
drive_download(
  file = file_week_OS_OP$id,
  path = "samp_week_OS_OP.rds",
  overwrite = TRUE
)

File downloaded:

• samp_week_OS_OP.rds <id: 1pdK26Q-WR4LeP9FOkdHd8_ZQ4XUzFWTh>

Saved locally as:

• samp_week_OS_OP.rds

In [19]:
obj_OS_OP <- readRDS("samp_week_OS_OP.rds")

### **Import dataset with covariate outliers and propensity outliers**

In [20]:
file_week_OX_OP <- files[files$name == 'samp_week_OX_OP.rds', ]

In [21]:
drive_download(
  file = file_week_OX_OP$id,
  path = "samp_week_OX_OP.rds",
  overwrite = TRUE
)

Auto-refreshing stale OAuth token.

File downloaded:

• samp_week_OX_OP.rds <id: 1FubojwRKwA1mk7fSZlHnGfaOpWP_N21p>

Saved locally as:

• samp_week_OX_OP.rds

In [22]:
obj_OX_OP <- readRDS("samp_week_OX_OP.rds")